apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  CONNECTION_STRING: "server=db-service;user=root;password=MySql2022;database=todoapidb"
  DB_HOST: db-service
  DB_USER: root
  DB_PASSWORD: MySql2022
