version: '3'

networks: 
  todonetwork:      
    driver: bridge
    name: todo-network

services:

  app-static:
    container_name: todoapp.static
    image: vitormoschetta/todoapp.static
    build:
      context: .
      dockerfile: Infra/docker/TodoStaticApp/Dockerfile
    network_mode: "host"

  app:
    container_name: todoapp
    image: vitormoschetta/todoapp
    build:
      context: .
      dockerfile: Infra/docker/TodoApp/Dockerfile    
    environment:
      API_URL: "http://todoapi:6001/api/"
    ports:
      - 6002:6002
    networks:
      - todonetwork

  api:
    container_name: todoapi
    image: vitormoschetta/todoapi
    build:
      context: .
      dockerfile: Infra/docker/TodoApi/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 6001:6001
    expose:
      - 6001    
    volumes:
      - ./TodoApi/appsettings.Docker.json:/public/appsettings.json
    networks:
      - todonetwork
    depends_on:
      - db

  db:
    container_name: todoapi.db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "todoapidb"
    volumes:      
      - ./Infra/docker/MySql/:/tmp/seeds/
    ports:
      - "3306:3306"  
    networks:
      - todonetwork
   
