version: '3'

networks: 
  todonetwork:      
    driver: bridge
    name: todo-network

services:

  app:
    container_name: todoapp
    image: vitormoschetta/todoapp
    build:
      context: .
      dockerfile: TodoAppBlazorServer.Dockerfile
    network_mode: "host"
    environment:
      SERVER_URL: "http://localhost:5000/api/"

  api:
    container_name: todoapi
    image: vitormoschetta/todoapi
    build:
      context: .
      dockerfile: TodoApi.Dockerfile
    ports:
      - 5000:8080
    expose:
      - 5000
    environment:
      CONNECTION_STRING: "server=todoapi.db;user=root;password=MySql2022;database=todoapidb"
    # volumes:
    #   - ./TodoApi/appsettings.DockerDevelopment.json:/public/appsettings.json
    networks:
      - todonetwork
    depends_on:
      - db

  db:
    container_name: todoapi.db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2022"
      MYSQL_DATABASE: "todoapidb"
    ports:
      - "3306:3306"  
    networks:
      - todonetwork
   
