version: '3'

networks: 
  todonetwork:      
    driver: bridge
    name: todo-network

services:

  staticapp:
    container_name: todo-static-app
    image: vitormoschetta/todo-static-app
    build:
      context: .
      dockerfile: TodoStaticApp.Dockerfile
    ports:
      - 6003:80
    networks:
      - todonetwork

  app:
    container_name: todoapp
    image: vitormoschetta/todoapp
    build:
      context: .
      dockerfile: TodoApp.Dockerfile
    #network_mode: "host"
    environment:
      API_URL: "http://todoapi:6001/api/"
    ports:
      - 6002:6002
    networks:
      - todonetwork

  api:
    container_name: todoapi
    image: vitormoschetta/todoapi
    build:
      context: .
      dockerfile: TodoApi.Dockerfile
    ports:
      - 6001:6001
    expose:
      - 6001
    environment:
      CONNECTION_STRING: "server=todoapi.db;user=root;password=MySql2022;database=todoapidb"
    # volumes:
    #   - ./TodoApi/appsettings.Docker.json:/public/appsettings.json
    networks:
      - todonetwork
    depends_on:
      - db

  db:
    container_name: todoapi.db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2022"
      MYSQL_DATABASE: "todoapidb"
    ports:
      - "3306:3306"  
    networks:
      - todonetwork
   
