version: '3'

networks: 
  todonetwork:      
    driver: bridge
    name: todo-network

services:

  app-static:
    container_name: todoapp.static
    image: vitormoschetta/todoapp.static
    build:
      context: .
      dockerfile: Infra/docker/TodoStaticApp/Dockerfile
    network_mode: "host"

  app:
    container_name: todoapp
    image: vitormoschetta/todoapp
    build:
      context: .
      dockerfile: Infra/docker/TodoApp/Dockerfile    
    environment:
      API_URL_CONNECTION: "http://todoapi:6001/api/"
    ports:
      - 6002:6002
    networks:
      - todonetwork

  api:
    container_name: todoapi
    image: vitormoschetta/todoapi
    build:
      context: .
      dockerfile: Infra/docker/TodoApi/Dockerfile
    environment:
      DB_CONNECTION__HOST: ${DB_CONNECTION__HOST}
      DB_CONNECTION__USER: ${DB_CONNECTION__USER}
      DB_CONNECTION__PASSWORD: ${DB_CONNECTION__PASSWORD}
      DB_CONNECTION__DATABASE: ${DB_CONNECTION__DATABASE}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_Kestrel__Certificates__Default__Password}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_Kestrel__Certificates__Default__Path}
    volumes:
      - ./Infra/docker/https:/https:ro
    ports:
      - 6001:6001
      - 60001:60001
    expose:
      - 6001
      - 60001
    networks:
      - todonetwork
    depends_on:
      - db

  db:
    container_name: todoapi.db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: MySql2022
      MYSQL_DATABASE: "todoapidb"
    volumes:      
      - ./Infra/docker/MySql/:/tmp/seeds/
    ports:
      - "3306:3306"  
    networks:
      - todonetwork
   
