apiVersion: v1
kind: Pod
metadata:
  name: todo-db
  labels:
    app: todo-db
spec:
  containers:
    - name: todo-db
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "MySql2022"
        - name: MYSQL_DATABASE
          value: "todoapidb"
      ports:
        - containerPort: 3306